env:
  DOCKER_COMPOSE_VERSION: 1.19.0

laguage: php

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install:
  - docker-compose up -f development.yml -d
  - curl ‐‐retry 10 ‐‐retry‐delay 5 ‐v http://localhost/codeigniter/index.php

after_success:
  - /bin/bash echo 'Processo efeuado com sucesso...'

