env:
  - DOCKER_COMPOSE_VERSION=1.19.0

language: bash

notifications:
  slack:
    on_success: always
    rooms:
      - huebrops:oQZYgN0fvoyFBVjuIUQREc8h
      - huebrops:oQZYgN0fvoyFBVjuIUQREc8h#general
      - huebrops:oQZYgN0fvoyFBVjuIUQREc8h#random

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install:
  - docker-compose -f development.yml up -d

script:
  - curl --retry 10 --retry-delay 5 -v http://127.0.0.1

after_success:
  - docker-compose -f development.yml down
  - /bin/bash echo "Processo construido com sucesso..."

