version: "3.4"
services:
  db:
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    restart: always
    environment:
      POSTGRES_DB: db_ci
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - dbnet

  web:
    build:
      context: .
      dockerfile: Dockerfile-ci
    ports:
      - 80:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: ./ci-data
        target: /var/www/html/codeigniter
        bind:
          propagation: "rprivate"
    environment:
      DB_USER: postgres
      DB_PASSWORD: ""
    depends_on:
      - db
    networks:
      - webnet
      - dbnet

volumes:
  dbdata:

networks:
  webnet:
  dbnet:

