version: "3.4"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/data
        bind:
          propagation: "rprivate"
    restart: always
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: db_ci
    secrets:
      - db_user
      - db_password
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - dbnet

  web:
    build:
      context: .
      dockerfile: Dockerfile-ci
    image: localhost:5000/my-codeigniter
    ports:
      - 80:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: ./ci-data
        target: /var/www/html/codeigniter
        bind:
          propagation: "rprivate"
    environment:
      DB_USER: /run/secrets/db_user
      DB_PASSWORD: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    depends_on:
      - db
    networks:
      - webnet
      - dbnet

secrets:
  db_user:
    file: ./.docker/secrets/db_user.txt
  db_password:
    file: ./.docker/secrets/db_password.txt

networks:
  webnet:
  dbnet:

