version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER: ci-test
          - POSTGRES_PASSWORD: test123
          - POSTGRES_DB: db_ci
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run
          name: Deploy container
          command: |
            docker-compose -f docker-compose.yml run -d --no-deps web
            curl ‐‐retry 10 ‐‐retry‐delay 5 ‐v http://localhost
        
